//--------------------------------------------- 1) Definir Las Variables Correspondintes---------------------------------------------
var Puesto_Oficial_RENGLON_011 = new Array ("-",
"011-ASESOR PROFESIONAL ESPECIALIZADO II",
"011-ASESOR PROFESIONAL ESPECIALIZADO IV",
"011-ASISTENTE PROFESIONAL I",
"011-ASISTENTE PROFESIONAL II",
"011-ASISTENTE PROFESIONAL III",
"011-ASISTENTE PROFESIONAL IV",
"011-ASISTENTE PROFESIONAL JEFE",
"011-DIRECTOR DE AREA DE SALUD",
"011-DIRECTOR DE DISPENSARIO I 4 HRS.",
"011-DIRECTOR DE HOSPITAL DISTRITAL",
"011-DIRECTOR DE HOSPITAL I",
"011-DIRECTOR DE HOSPITAL I 4 HRS.",
"011-DIRECTOR DE HOSPITAL II",
"011-DIRECTOR REGIONAL",
"011-DIRECTOR TECNICO II",
"011-JEFE DE AREA",
"011-JEFE TECNICO I",
"011-JEFE TECNICO II",
"011-JEFE TECNICO PROFESIONAL I",
"011-JEFE TECNICO PROFESIONAL I 4 HRS.",
"011-JEFE TECNICO PROFESIONAL II",
"011-JEFE TECNICO PROFESIONAL III",
"011-OFICIAL MAYOR",
"011-OFICINISTA I",
"011-OFICINISTA II",
"011-OFICINISTA III",
"011-OFICINISTA IV",
"011-PARAMEDICO I",
"011-PARAMEDICO I 2 HRS.",
"011-PARAMEDICO I 3 HRS.",
"011-PARAMEDICO I 4 HRS.",
"011-PARAMEDICO II",
"011-PARAMEDICO III",
"011-PARAMEDICO III 4 HRS.",
"011-PARAMEDICO IV",
"011-PARAMEDICO IV 4 HRS.",
"011-PARAMEDICO JEFE I",
"011-PARAMEDICO JEFE II",
"011-PARAMEDICO JEFE III",
"011-PROFESIONAL I",
"011-PROFESIONAL I 2 HRS.",
"011-PROFESIONAL I 3 HRS.",
"011-PROFESIONAL I 4 HRS.",
"011-PROFESIONAL I 6 HRS.",
"011-PROFESIONAL II",
"011-PROFESIONAL II 1 HRA.",
"011-PROFESIONAL II 2 HRS.",
"011-PROFESIONAL II 4 HRS.",
"011-PROFESIONAL II 6 HRS.",
"011-PROFESIONAL III",
"011-PROFESIONAL III 1 HRA.",
"011-PROFESIONAL III 2 HRS.",
"011-PROFESIONAL III 4 HRS.",
"011-PROFESIONAL III 6 HRS.",
"011-PROFESIONAL JEFE I",
"011-PROFESIONAL JEFE I 2 HRS.",
"011-PROFESIONAL JEFE I 3 HRS.",
"011-PROFESIONAL JEFE I 4 HRS.",
"011-PROFESIONAL JEFE I 6 HRS.",
"011-PROFESIONAL JEFE II",
"011-PROFESIONAL JEFE II 2 HRS.",
"011-PROFESIONAL JEFE II 3 HRS.",
"011-PROFESIONAL JEFE II 4 HRS.",
"011-PROFESIONAL JEFE II 6 HRS.",
"011-PROFESIONAL JEFE III",
"011-PROFESIONAL JEFE III 2 HRS.",
"011-PROFESIONAL JEFE III 3 HRS.",
"011-PROFESIONAL JEFE III 4 HRS.",
"011-PROFESIONAL JEFE III 6 HRS.",
"011-SECRETARIO EJECUTIVO I",
"011-SECRETARIO EJECUTIVO II",
"011-SECRETARIO EJECUTIVO III",
"011-SECRETARIO EJECUTIVO IV",
"011-SECRETARIO EJECUTIVO MINISTERIAL I",
"011-SECRETARIO EJECUTIVO MINISTERIAL II",
"011-SECRETARIO EJECUTIVO V",
"011-SECRETARIO OFICINISTA",
"011-SUB DIRECTOR DE HOSPITAL I",
"011-SUB DIRECTOR DE HOSPITAL II",
"011-SUB DIRECTOR GENERAL",
"011-SUBDIRECTOR TECNICO II",
"011-TECNICO EN INFORMATICA I",
"011-TECNICO I",
"011-TECNICO II",
"011-TECNICO III",
"011-TECNICO III 4 HRS.",
"011-TECNICO III 6 HRS.",
"011-TECNICO PROFESIONAL I",
"011-TECNICO PROFESIONAL I 4 HRS.",
"011-TECNICO PROFESIONAL I 6 HRS.",
"011-TECNICO PROFESIONAL II",
"011-TECNICO PROFESIONAL II 1 HRA.",
"011-TECNICO PROFESIONAL III",
"011-TECNICO PROFESIONAL INFORMATICA III",
"011-TRABAJADOR ESPECIALIZADO I",
"011-TRABAJADOR ESPECIALIZADO I 6 HRS.",
"011-TRABAJADOR ESPECIALIZADO II",
"011-TRABAJADOR ESPECIALIZADO III",
"011-TRABAJADOR ESPECIALIZADO JEFE I",
"011-TRABAJADOR ESPECIALIZADO JEFE II",
"011-TRABAJADOR OPERATIVO II",
"011-TRABAJADOR OPERATIVO III",
"011-TRABAJADOR OPERATIVO IV",
"011-TRABAJADOR OPERATIVO JEFE I",
"011-TRABAJADOR OPERATIVO JEFE II",
"011-VICEMINISTRO",
"011-MINISTRO DE SALUD PUBLICA Y A.S.",
"011-ASESOR PROFESIONAL ESPEC I 6 HRS",
"011-PARAMEDICO II 4 HRS.",
"011-PARAMEDICO IV 6 HRS.",
"011-PARAMEDICO JEFE I 4 HRS.",
"011-PEÓN",
"011-PROFESIONAL III 3 HRS.",
"011-PROFESIONAL III 4 HORAS",
"011-PROFESIONAL JEFE III 4 HRS.",
"011-TECNICO I 6 HRS.",
"011-TECNICO PROFESIONAL  EN INFORMATICA II",
"011-TECNICO PROFESIONAL II 6 HRS.",
"011-TRABAJADOR ESPECIALIZADO II 4 HRS.",
"011-TRABAJADOR ESPECIALIZADO III 4 HRS",
"011-TRABAJADOR ESPECIALIZADO III 6 HRS",);

var Puesto_Oficial_RENGLON_021 = new Array ("-", 
"021-ANALISTA DE CONTABILIDAD",
"021-ANALISTA DE PRESUPUESTO",
"021-ENCARGADO DE COMPRAS",
"021-ENCARGADO DE PRESUPUESTO",
"021-ENCARGADO DE TESORERÍA",
"021-JEFE ADMINISTRATIVO",
"021-JEFE DE GESTIÓN DE PROGRAMAS, PROYECTOS Y COOPERACIÓN INTERNACIONAL",
"021-JEFE DE INGENIERÍA DE PROYECTOS",
"021-JEFE DE RESIDENTE",
"021-JEFE DE SEGUIMIENTO DE INGENIERÍA",
"021-MÉDICO DE URGENCIA",
"021-MÉDICO RESIDENTE I",
"021-MÉDICO RESIDENTE II",
"021-MÉDICO RESIDENTE III",
"021-MÉDICO RESIDENTE IV",
"021-MÉDICO TURNISTA 4 HORAS",
"021-PROFESIONAL AMBIENTAL",
"021-PROFESIONAL EN ADMINISTRACIÓN DE PROGRAMAS Y PROYECTOS",
"021-PROFESIONAL EN INGENIERÍA INDUSTRIAL",
"021-PROFESIONAL II",
"021-PROFESIONAL JURÍDICO",
"021-SECRETARIA",
"021-SECRETARIA EJECUTIVA",
"021-JEFE FINANCIERO",
"021-TÉCNICO DE ALMACÉN",
"021-ANALISTA DE TESORERÍA",
"021-PROFESIONAL EN INGENIERÍA CIVIL",
"021-PROFESIONAL EN INGENIERÍA MECÁNICA",
"021-PROFESIONAL EN PROGRAMAS, PROYECTOS Y COOPERACIÓN INTERNACIONAL",
"021-PROFESIONAL EN ARQUITECTURA",
"021-MENSAJERO",
"021-CONSERJE",
"021-ENCARGADO DE INVENTARIOS",
"021-PILOTO",
"021-TÉCNICO DE INVENTARIOS",
"021-ENCARGADO DE CONTABILIDAD",
"021-ENCARGADO DE ALMACEN",
"021-ANALISTA DE COMPRAS",
"021-PROFESIONAL EN SERVICIOS DE SALUD",
"021-PROFESIONAL EN INGENIERÍA ELÉCTRICA",
"021-PROFESIONAL EN INGENIERÍA SANITARIA");

var Puesto_Oficial_RENGLON_022 = new Array ("-",
"022-DIRECTOR EJECUTIVO I",
"022-DIRECTOR EJECUTIVO II",
"022-OFICINISTA IV",
"022-SUBDIRECTOR EJECUTIVO I",
"022-SUBDIRECTOR EJECUTIVO II",
"022-TECNICO I",
"022-TECNICO III",
"022-PROFESIONAL II",
"022-TRABAJADOR ESPECIALIZADO II");


var Puesto_Oficial_RENGLON_031 = new Array ("-", 
"031-ALBAÑIL I",
"031-AUXILIAR DE BODEGA",
"031-AUXILIAR DE OPERACIÓN DE ",
"031-AUXILIAR MISCELÁNEO",
"031-BODEGUERO IV",
"031-CARPINTERO I",
"031-COCINERO",
"031-CONDUCTOR DE VEHÍCULOS ",
"031-CONSERJE",
"031-ELECTRICISTA I",
"031-FONTANERO I",
"031-HERRERO I",
"031-LAVANDERA I",
"031-MECÁNICO AUTOMOTRÍZ I",
"031-MENSAJERO I",
"031-OPERADOR DE EQUIPO DE ",
"031-PEÓN VIGILANTE I",
"031-PEÓN VIGILANTE II",
"031-PEÓN VIGILANTE V",
"031-PEÓN VIVANDERA",
"031-PILOTO I VEHÍCULOS ",
"031-PINTOR I",
"031-TRABAJADOR ECÓNOMO",
"031-ALBAÑIL III",
"031-ALBAÑIL IV",
"031-ALBAÑIL V",
"031-AUXILIAR DE ALBAÑILERÍA",
"031-AUXILIAR DE CAPORAL",
"031-AUXILIAR DE CARPINTERÍA",
"031-AUXILIAR DE ELECTRICIDAD",
"031-AUXILIAR DE FONTANERÍA",
"031-AUXILIAR DE HERRERÍA",
"031-AUXILIAR DE MECÁNICA",
"031-AUXILIAR DE OPERACIÓN DE MAQUINARIA Y EQUIPO",
"031-BODEGUERO I",
"031-BODEGUERO II",
"031-BODEGUERO III",
"031-CONDUCTOR DE VEHÍCULOS LIVIANOS",
"031-CONDUCTOR DE VEHÍCULOS PESADOS",
"031-ELECTRICISTA II",
"031-ELECTRICISTA III",
"031-ENCARGADO I DE OPERACIONES DE MAQUINARIA Y EQUIPO",
"031-JARDINERO I",
"031-JARDINERO II",
"031-LAVANDERA II",
"031-MAESTRO DE OBRAS",
"031-MECÁNICO AUTOMOTRÍZ II",
"031-MECÁNICO AUTOMOTRÍZ III",
"031-MENSAJERO II",
"031-OPERADOR DE EQUIPO",
"031-OPERADOR DE EQUIPO DE ESTADÍSTICA",
"031-OPERADOR DE MAQUINARIA",
"031-PEÓN",
"031-PEÓN VIGILANTE III",
"031-PEÓN VIGILANTE IV",
"031-PILOTO I VEHÍCULOS LIVIANOS",
"031-PILOTO II VEHÍCULOS PESADOS",
"031-Puesto Oficial",
"031-SASTRE",
"031-TRABAJADOR  VIVANDERA",
"031-TRABAJADOR DE MANTENIMIENTO DE TELECOMUNICACIONES I");

var Puesto_Oficial_RENGLON_029 = new Array ("-", 
"029-SERVICIOS TÉCNICOS", 
"029-SERVICIOS PROFESIONALES");

var Puesto_Oficial_RENGLON_036 = new Array ("NO APLICA");

var Puesto_Oficial_RENGLON_081 = new Array ("-",
"081-SERVICIOS TÉCNICOS", 
"081-SERVICIOS PROFESIONALES");

var Puesto_Oficial_RENGLON_181 = new Array ("NO APLICA");

var Puesto_Oficial_RENGLON_182 = new Array ("-", 
"182-SERVICIOS TÉCNICOS", 
"182-SERVICIOS PROFESIONALES");

var Puesto_Oficial_RENGLON_183 = new Array ("-", 
"183-SERVICIOS TÉCNICOS", 
"183-SERVICIOS PROFESIONALES");

var Puesto_Oficial_RENGLON_184 = new Array ("-", 
"184-SERVICIOS TÉCNICOS", 
"184-SERVICIOS PROFESIONALES");

var Puesto_Oficial_RENGLON_185 = new Array ("-", 
"185-SERVICIOS TÉCNICOS", 
"185-SERVICIOS PROFESIONALES");

var Puesto_Oficial_RENGLON_186 = new Array ("-", 
"186-SERVICIOS TÉCNICOS", 
"186-SERVICIOS PROFESIONALES");

var Puesto_Oficial_RENGLON_187 = new Array ("NO APLICA");

var Puesto_Oficial_RENGLON_188 = new Array ("-", 
"188-SERVICIOS TÉCNICOS", 
"188-SERVICIOS PROFESIONALES");

var Puesto_Oficial_RENGLON_189 = new Array ("-", 
"189-SERVICIOS TÉCNICOS", 
"189-SERVICIOS PROFESIONALES");


// ---------------------------------------------2) crear una funcion que permita ejecutar el cambio dinamico---------------------------------------------

function cambia(){
    var Renglon;
    //Se toma el vamor de la "cosa seleccionada"
    Renglon = document.uploadForm.Renglon[document.uploadForm.Renglon.selectedIndex].value;
    //se chequea si la "cosa" esta definida
    if(Renglon!=0){
        //selecionamos las cosas Correctas
        mis_opts=eval("Puesto_Oficial_" + Renglon);
        //se calcula el numero de cosas
        num_opts=mis_opts.length;
        //marco el numero de opt en el select
        document.uploadForm.Puesto_Oficial.length = num_opts;
        //para cada opt del array, la pongo en el select
        for(i=0; i<num_opts; i++){
            document.uploadForm.Puesto_Oficial.options[i].value=mis_opts[i];
            document.uploadForm.Puesto_Oficial.options[i].text=mis_opts[i];
        }
        }else{
            //si no habia ninguna opt seleccionada, elimino las cosas del select
            document.uploadForm.opt.length = 1;
            //ponemos un guion en la unica opt que he dejado
            document.uploadForm.opt.options[0].value="-";
            document.uploadForm.opt.options[0].text="-";
        }
        //hacer un reset de las opts
        document.uploadForm.Puesto_Oficial.options[0].selected = true;
        
    }

